"""Initial migration: Create trade_safety_checks table

Revision ID: 46ef2cade112
Revises: 
Create Date: 2025-11-24 00:24:20.783340

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "46ef2cade112"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "trade_safety_checks",
        sa.Column("user_id", sa.String(length=255), nullable=True),
        sa.Column("input_text", sa.Text(), nullable=False),
        sa.Column("llm_analysis", sa.JSON(), nullable=False),
        sa.Column("risk_score", sa.Integer(), nullable=False),
        sa.Column("expert_advice", sa.Text(), nullable=True),
        sa.Column(
            "expert_reviewed", sa.Boolean(), server_default="false", nullable=False
        ),
        sa.Column("expert_reviewed_at", sa.DateTime(), nullable=True),
        sa.Column("expert_reviewed_by", sa.String(length=255), nullable=True),
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_trade_safety_checks")),
    )
    with op.batch_alter_table("trade_safety_checks", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_trade_safety_checks_expert_reviewed"),
            ["expert_reviewed"],
            unique=False,
        )
        batch_op.create_index(
            batch_op.f("ix_trade_safety_checks_user_id"), ["user_id"], unique=False
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("trade_safety_checks", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_trade_safety_checks_user_id"))
        batch_op.drop_index(batch_op.f("ix_trade_safety_checks_expert_reviewed"))

    op.drop_table("trade_safety_checks")
    # ### end Alembic commands ###
